/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucue.p3.GUI;

import edu.ucue.p3.Archivo.SeleccionArchivo;
import edu.ucue.p3.huffman.Huffman;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paul
 */
public class AppHuffman extends javax.swing.JFrame {

    File archivo;
    /**
     * Creates new form Huffman
     */
    public AppHuffman() {
        initComponents();
    }
    
    private void generarTabla(String[][] listaTablas) throws FileNotFoundException, IOException {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        Object[] tabla = new Object[4];
        tabla[0] = "Caracter";
        tabla[1] = "Frecuencia";
        tabla[2] = "Bits Normal";
        tabla[3] = "Bits Huffman";
        
        modelo.setColumnIdentifiers(tabla);
        
        if(listaTablas==null || listaTablas.length == 0){
            this.tSalida.setModel(modelo);
            return;
        }
        
        for (int i=0; i<listaTablas.length; i++) {
            modelo.addRow(listaTablas[i]);
        }
        this.tSalida.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bArbirArchivo = new javax.swing.JButton();
        bComprimir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tSalida = new javax.swing.JTable();
        jlab3 = new javax.swing.JLabel();
        LbRazonCompresion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LBOriginal = new javax.swing.JLabel();
        LbComprimido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bArbirArchivo.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        bArbirArchivo.setText("Abrir Archivo");
        bArbirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArbirArchivoActionPerformed(evt);
            }
        });

        bComprimir.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        bComprimir.setText("Comprimir");
        bComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprimirActionPerformed(evt);
            }
        });

        tSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caracter", "Frecuencia", "Bits Normal", "Bits Huffman"
            }
        ));
        jScrollPane2.setViewportView(tSalida);

        jlab3.setText("Porcentaje de Compresión");

        LbRazonCompresion.setText("0");

        jLabel2.setText("Original");

        jLabel3.setText("Comprimido");

        LBOriginal.setText("0");

        LbComprimido.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bArbirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bComprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jlab3)
                        .addGap(55, 55, 55)
                        .addComponent(LbRazonCompresion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbComprimido)
                    .addComponent(LBOriginal))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bArbirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(bComprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LBOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlab3)
                    .addComponent(LbRazonCompresion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LbComprimido))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bArbirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArbirArchivoActionPerformed
        // TODO add your handling code here:
        archivo = new File((new SeleccionArchivo()).getPathArchivo(this));
        bComprimir.setEnabled(true);
        
    }//GEN-LAST:event_bArbirArchivoActionPerformed

    private void bComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprimirActionPerformed
        try {
            // TODO add your handling code here:
            Huffman huffman = new Huffman(archivo);
            //System.out.println(huffman.gethC().getTexto().toString());
            bComprimir.setEnabled(false);
            generarTabla(huffman.getTabla());
            LbRazonCompresion.setText(String.valueOf(huffman.razonDeCompresion()));
            File original = new File("original.txt");
            File comprimido = new File("comprimido");
            LBOriginal.setText(String.valueOf(original.length()));
            LbComprimido.setText(String.valueOf(comprimido.length()));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Archivo no disponible");
        }
        
    }//GEN-LAST:event_bComprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppHuffman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBOriginal;
    private javax.swing.JLabel LbComprimido;
    private javax.swing.JLabel LbRazonCompresion;
    private javax.swing.JButton bArbirArchivo;
    private javax.swing.JButton bComprimir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlab3;
    private javax.swing.JTable tSalida;
    // End of variables declaration//GEN-END:variables
}
